---
# включаем(true)\выключаем(false)
dist_upd: true # Обновление кеша пакетов и установка обязательных пакетов
dist_upgrd: true # обновление установленных приложений и дистрибутива
kernel_upd: true # обновление ядра
# install_soft: false # установка софта
