---
# включаем(true)\выключаем(false)
dist_upd: true # Обновление кеша пакетов
dist_upgrd: true # обновление установленных приложений и дистрибутива
kernel_upd: true # обновление ядра
install_bind: false # установка и настройка кеширующего bind