#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/smb_skv
- name: Запуск samba обработчиком
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  loop:
    - samba
  listen: start_samba_alt
