---
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "{{ su_wheel_user }}"
ansible_become_password: "{{ su_password }}"
ansible_ssh_private_key_file: "~/.ssh/id_alt-adm6_2026_host_ed25519"