$ANSIBLE_VAULT;1.1;AES256
66313831633636373336623439346137353565383738353534323432376664663862383462656139
6237343961303537633433393261356533653035623663330a623030303362393339346331656663
38383364376237303036333831323161303935653161373738616262323139643637643337336262
3431333061333337370a326363343331666334343635336335373639663832393566386232613739
66343066343333613462646632663130303539653833353432646439333564333539653538333637
38613632343931623564343933646539333930373331303261306339623463646662366434343462
33356239336266326232363133303439653766666666333437616364393132363466333033393939
63613637316335643333313837313862353735316135303637623866356661623633616264613537
38346364393038646430346164333364376162383161613962643131363535653239346630396163
38363965656233653163623134383561653631386136313064396138363734656537306361343538
656366653261356530636534343364343238
