$ANSIBLE_VAULT;1.1;AES256
62376339373066313831303934383936323136666532663263306538643832396338313664323431
3932623461333166396164336563386136356330663963340a356665633038636664393565633532
31643361613230336364316363633563363365386632346435626431636639393136613439343866
3837663431383462660a373635653038613766346635633035626261383862363536626337313261
66316462616230373038613232663538363464663532643333633238356332343134646439376564
34663763663562313361363637366164336131656664366431346265326334316332383832336461
393266336237633062306532613434646665
