# ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_kvm_host_to_vms {{ su_wheel_user }}@192.168.121.2"'
# ansible_ssh_private_key_file: "~/.ssh/id_vm"
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "{{ su_wheel_user }}"
ansible_become_password: "{{ su_password }}"
