---
- name: Обновление кеша пакетов
  apt_rpm:
    update_cache: true

- name: Обновление пакетов
  apt_rpm:
    dist_upgrade: true
  when: dist_upd | bool


- name: Установка дополнений для узлов
  apt_rpm:
    name: 
      - python3
      - python3-module-yaml
      - python3-module-jinja2
      - python3-module-json5
      - python3-module-passlib
      - samba-client
      - bind-utils
    state: installed

- name: Обновление ядра
  apt_rpm:
    update_kernel: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/sbin"
  ignore_errors: true
  when: kernel_upd | bool