---
- name: Обновление кеша пакетов
  apt_rpm:
    update_cache: true

- name: Обновление пакетов
  apt_rpm:
    dist_upgrade: true
  when: dist_upd | bool

- name: Обновление ядра
  apt_rpm:
    update_kernel: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/sbin"
  ignore_errors: true
  when: kernel_upd | bool